version: '3.4'

services:
  real_time_app:
    image: real-time:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/"
      - ".docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - real-time-chat
    deploy:
      resources:
        limits:
          cpus: '0.2'

  real_time_webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/"
      - ".docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - real-time-chat
    deploy:
      resources:
        limits:
          cpus: '0.2'

  real_time_db:
    image: mariadb:10.2
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: chatdb
      MYSQL_USER: me
      MYSQL_PASSWORD: me
      MYSQL_ROOT_PASSWORD: me
    volumes:
      - ".docker/mysql:/var/lib/mysql"
    networks:
      - real-time-chat
    deploy:
      resources:
        limits:
          cpus: '0.2'
  real_time_echo_server:
    image: laravel_echo_app/dev:latest
    build:
      context: .docker/echo_server/
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    networks:
      - real-time-chat
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    networks:
      - real-time-chat

networks:
  real-time-chat:
    driver: bridge

